"""
Pattern Detector - Advanced Pattern Recognition
DGA detection, typosquatting, phishing, and anomaly detection
"""

import re
import logging
from typing import Dict, Any, List, Optional, Tuple
from collections import Counter
import math


class PatternDetector:
    """
    Detect suspicious patterns in domains, URLs, and infrastructure.
    
    Techniques:
    - DGA (Domain Generation Algorithm) detection
    - Typosquatting detection
    - Phishing detection
    - Certificate anomalies
    - WHOIS anomalies
    """
    
    # Suspicious TLDs
    SUSPICIOUS_TLDS = {
        'tk', 'ml', 'ga', 'cf', 'gq',  # Free TLDs
        'xyz', 'top', 'work', 'click',  # Commonly abused
    }
    
    # Popular brands for phishing detection
    POPULAR_BRANDS = {
        'google', 'facebook', 'amazon', 'microsoft', 'apple',
        'paypal', 'netflix', 'instagram', 'twitter', 'linkedin',
        'dropbox', 'adobe', 'yahoo', 'ebay', 'walmart',
    }
    
    def __init__(self):
        """Initialize pattern detector"""
        self.logger = logging.getLogger(__name__)
    
    def detect_dga(self, domain: str) -> Dict[str, Any]:
        """
        Detect if domain is likely generated by DGA.
        
        Args:
            domain: Domain name
            
        Returns:
            Detection result with score and features
        """
        # Extract domain without TLD
        parts = domain.split('.')
        if len(parts) < 2:
            return {'is_dga': False, 'score': 0.0}
        
        domain_name = parts[0]
        
        # Calculate features
        features = {
            'length': len(domain_name),
            'entropy': self._calculate_entropy(domain_name),
            'consonant_ratio': self._consonant_ratio(domain_name),
            'digit_ratio': self._digit_ratio(domain_name),
            'vowel_ratio': self._vowel_ratio(domain_name),
            'unique_char_ratio': len(set(domain_name)) / len(domain_name) if domain_name else 0,
            'has_numbers': any(c.isdigit() for c in domain_name),
            'has_hyphens': '-' in domain_name,
        }
        
        # Scoring
        score = 0.0
        
        # High entropy (random-looking)
        if features['entropy'] > 3.5:
            score += 0.3
        
        # Unusual consonant ratio
        if features['consonant_ratio'] > 0.7 or features['consonant_ratio'] < 0.3:
            score += 0.2
        
        # High digit ratio
        if features['digit_ratio'] > 0.3:
            score += 0.2
        
        # Long domain
        if features['length'] > 15:
            score += 0.1
        
        # High unique character ratio (not repeating patterns)
        if features['unique_char_ratio'] > 0.8:
            score += 0.2
        
        return {
            'is_dga': score > 0.6,
            'score': min(score, 1.0),
            'features': features,
            'confidence': 'high' if score > 0.8 else 'medium' if score > 0.6 else 'low'
        }
    
    def detect_typosquatting(
        self,
        domain: str,
        target_domains: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Detect typosquatting attempts.
        
        Args:
            domain: Domain to check
            target_domains: List of legitimate domains to check against
            
        Returns:
            Detection result
        """
        if target_domains is None:
            target_domains = list(self.POPULAR_BRANDS)
        
        domain_name = domain.split('.')[0].lower()
        
        matches = []
        
        for target in target_domains:
            target = target.lower()
            
            # Levenshtein distance
            distance = self._levenshtein_distance(domain_name, target)
            
            # Similarity ratio
            max_len = max(len(domain_name), len(target))
            similarity = 1 - (distance / max_len) if max_len > 0 else 0
            
            # Check for common typosquatting techniques
            techniques = []
            
            # Character substitution (homoglyphs)
            if self._has_homoglyphs(domain_name, target):
                techniques.append('homoglyph')
                similarity += 0.1
            
            # Character omission
            if distance == 1 and len(domain_name) < len(target):
                techniques.append('omission')
            
            # Character insertion
            if distance == 1 and len(domain_name) > len(target):
                techniques.append('insertion')
            
            # Character swap
            if self._is_character_swap(domain_name, target):
                techniques.append('swap')
            
            # Keyboard proximity
            if self._keyboard_proximity(domain_name, target):
                techniques.append('keyboard_proximity')
            
            if similarity > 0.7 or techniques:
                matches.append({
                    'target': target,
                    'similarity': min(similarity, 1.0),
                    'distance': distance,
                    'techniques': techniques,
                })
        
        # Sort by similarity
        matches.sort(key=lambda x: x['similarity'], reverse=True)
        
        is_typosquatting = len(matches) > 0 and matches[0]['similarity'] > 0.7
        
        return {
            'is_typosquatting': is_typosquatting,
            'matches': matches[:5],  # Top 5
            'confidence': 'high' if matches and matches[0]['similarity'] > 0.9 else 'medium'
        }
    
    def detect_phishing(self, domain: str, url: Optional[str] = None) -> Dict[str, Any]:
        """
        Detect phishing indicators.
        
        Args:
            domain: Domain name
            url: Full URL (optional)
            
        Returns:
            Detection result
        """
        indicators = []
        score = 0.0
        
        domain_lower = domain.lower()
        
        # Check for brand names in domain
        for brand in self.POPULAR_BRANDS:
            if brand in domain_lower and not domain_lower.startswith(brand):
                indicators.append(f"brand_name_in_subdomain:{brand}")
                score += 0.3
        
        # Suspicious TLD
        tld = domain.split('.')[-1].lower()
        if tld in self.SUSPICIOUS_TLDS:
            indicators.append(f"suspicious_tld:{tld}")
            score += 0.2
        
        # Excessive hyphens
        if domain.count('-') > 2:
            indicators.append("excessive_hyphens")
            score += 0.1
        
        # IP address in domain
        if re.search(r'\d{1,3}[-\.]\d{1,3}[-\.]\d{1,3}[-\.]\d{1,3}', domain):
            indicators.append("ip_in_domain")
            score += 0.3
        
        # @ symbol (credential phishing)
        if url and '@' in url:
            indicators.append("at_symbol_in_url")
            score += 0.4
        
        # URL shortener
        url_shorteners = ['bit.ly', 'tinyurl', 'goo.gl', 't.co', 'ow.ly']
        if any(short in domain_lower for short in url_shorteners):
            indicators.append("url_shortener")
            score += 0.2
        
        # Punycode (IDN homograph attack)
        if domain.startswith('xn--'):
            indicators.append("punycode")
            score += 0.3
        
        return {
            'is_phishing': score > 0.5,
            'score': min(score, 1.0),
            'indicators': indicators,
            'confidence': 'high' if score > 0.7 else 'medium' if score > 0.5 else 'low'
        }
    
    def detect_certificate_anomalies(self, cert_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Detect SSL certificate anomalies.
        
        Args:
            cert_data: Certificate data
            
        Returns:
            Anomaly detection result
        """
        anomalies = []
        score = 0.0
        
        # Self-signed
        if cert_data.get('issuer') == cert_data.get('subject'):
            anomalies.append("self_signed")
            score += 0.4
        
        # Expired
        if 'not_after' in cert_data:
            from datetime import datetime
            try:
                expiry = datetime.strptime(cert_data['not_after'], '%b %d %H:%M:%S %Y %Z')
                if expiry < datetime.now():
                    anomalies.append("expired")
                    score += 0.5
            except:
                pass
        
        # Wildcard abuse (too many SANs)
        if 'subject_alt_names' in cert_data:
            san_count = len(cert_data['subject_alt_names'])
            if san_count > 50:
                anomalies.append(f"excessive_sans:{san_count}")
                score += 0.3
        
        # Short validity period (< 30 days)
        if 'not_before' in cert_data and 'not_after' in cert_data:
            try:
                from datetime import datetime
                start = datetime.strptime(cert_data['not_before'], '%b %d %H:%M:%S %Y %Z')
                end = datetime.strptime(cert_data['not_after'], '%b %d %H:%M:%S %Y %Z')
                validity_days = (end - start).days
                
                if validity_days < 30:
                    anomalies.append(f"short_validity:{validity_days}days")
                    score += 0.2
            except:
                pass
        
        return {
            'has_anomalies': len(anomalies) > 0,
            'score': min(score, 1.0),
            'anomalies': anomalies,
        }
    
    # Helper methods
    
    def _calculate_entropy(self, s: str) -> float:
        """Calculate Shannon entropy"""
        if not s:
            return 0.0
        
        freq = Counter(s)
        length = len(s)
        
        entropy = -sum(
            (count / length) * math.log2(count / length)
            for count in freq.values()
        )
        
        return entropy
    
    def _consonant_ratio(self, s: str) -> float:
        """Calculate ratio of consonants"""
        if not s:
            return 0.0
        
        consonants = sum(1 for c in s.lower() if c.isalpha() and c not in 'aeiou')
        letters = sum(1 for c in s if c.isalpha())
        
        return consonants / letters if letters > 0 else 0.0
    
    def _vowel_ratio(self, s: str) -> float:
        """Calculate ratio of vowels"""
        if not s:
            return 0.0
        
        vowels = sum(1 for c in s.lower() if c in 'aeiou')
        letters = sum(1 for c in s if c.isalpha())
        
        return vowels / letters if letters > 0 else 0.0
    
    def _digit_ratio(self, s: str) -> float:
        """Calculate ratio of digits"""
        if not s:
            return 0.0
        
        digits = sum(1 for c in s if c.isdigit())
        return digits / len(s)
    
    def _levenshtein_distance(self, s1: str, s2: str) -> int:
        """Calculate Levenshtein distance"""
        if len(s1) < len(s2):
            return self._levenshtein_distance(s2, s1)
        
        if len(s2) == 0:
            return len(s1)
        
        previous_row = range(len(s2) + 1)
        for i, c1 in enumerate(s1):
            current_row = [i + 1]
            for j, c2 in enumerate(s2):
                insertions = previous_row[j + 1] + 1
                deletions = current_row[j] + 1
                substitutions = previous_row[j] + (c1 != c2)
                current_row.append(min(insertions, deletions, substitutions))
            previous_row = current_row
        
        return previous_row[-1]
    
    def _has_homoglyphs(self, s1: str, s2: str) -> bool:
        """Check for homoglyph substitution"""
        homoglyphs = {
            '0': 'o', 'o': '0',
            '1': 'l', 'l': '1', 'i': '1',
            'rn': 'm', 'm': 'rn',
        }
        
        # Simple check
        for char1, char2 in homoglyphs.items():
            if char1 in s1 and char2 in s2:
                return True
        
        return False
    
    def _is_character_swap(self, s1: str, s2: str) -> bool:
        """Check if strings differ by character swap"""
        if len(s1) != len(s2):
            return False
        
        diffs = [(i, s1[i], s2[i]) for i in range(len(s1)) if s1[i] != s2[i]]
        
        if len(diffs) == 2:
            i1, c1_1, c2_1 = diffs[0]
            i2, c1_2, c2_2 = diffs[1]
            return c1_1 == c2_2 and c1_2 == c2_1
        
        return False
    
    def _keyboard_proximity(self, s1: str, s2: str) -> bool:
        """Check for keyboard proximity typos"""
        keyboard = {
            'q': 'wa', 'w': 'qes', 'e': 'wrd', 'r': 'etf',
            'a': 'qsz', 's': 'awdxz', 'd': 'sfce', 'f': 'dgvr',
            # Add more as needed
        }
        
        if len(s1) != len(s2):
            return False
        
        for c1, c2 in zip(s1, s2):
            if c1 != c2:
                if c2 not in keyboard.get(c1, ''):
                    return False
        
        return True
